/* =========================================================
   공유 데이터 (index.html · case.html 둘 다 로드)
   - 프로젝트/그래픽 내용은 모두 이 파일에서 수정하면 됩니다.
   - 케이스 본문은 placeholder. 실제 내용/이미지로 교체하세요.
   ========================================================= */

/* 프로젝트 8개. featured:true → SELECTED WORKS 핀 전환에 노출.
   type: Web | App | Commerce  (ARCHIVE 필터 기준)
   mock: web | app | shop      (목업 와이어프레임 종류)
   theme: light | dark         (다크는 어두운 무드 목업)
   gallery: ['image/a.png', ...]  (선택) 케이스 페이지 VISUALS 스트립 이미지. 없으면 placeholder. */
const PROJECTS = {
  'dingo': {
    no: 'PROJECT 01', title: 'Dingo 리디자인', category: 'Web Redesign', type: 'Web', year: '2026',
    link: 'https://slrspdla-nunu.github.io/Dingo/',
    team: false, featured: false, theme: 'light', mock: 'web',
    summary: '영상 콘텐츠 브랜드 Dingo 홈페이지 리디자인.',
    pages: ['홈', '회사소개', '딩고(콘텐츠)', '광고 솔루션', '팬 페이지'],
    gallery: ['image/dingo1.png', 'image/dingo2.png', 'image/dingo3.png'],
    compare: { before: 'image/dingo_before.png', after: 'image/dingo_pc.png' },
    role: 'UI 디자인 · AI 활용 퍼블리싱', contribution: 100,
    tools: ['Figma', 'html/css' , 'Gemini', 'ChatGPT','Claude'],
    problem: '원본(makeus.com)은 기존 템플릿 기반 기업 사이트 구조로, 메뉴·정보는 많지만 첫 화면에서 브랜드 감성과 최신 영상·음악이 잘 드러나지 않았습니다.',
    goal: '대메뉴 구조(Company·Content·Business·Contact)는 그대로 두되, 히어로와 큐레이션으로 콘텐츠 감성과 진입 동선을 끌어올리는 것.',
    process: [
      { step: 'Analyze', desc: '원본(makeus.com)의 IA·진입 동선과 템플릿 기반 구조의 한계 정리.' },
      { step: 'Wireframe', desc: '히어로·딩고 큐레이션·스튜디오 지표·플레이리스트 순으로 우선순위 재설계.' },
      { step: 'UI Design', desc: '브랜드 컬러/타이포 시스템 재정의와 데코 그래픽 무드 설정.' },
      { step: 'Interaction', desc: 'Killing Voice 바이닐 플레이어·큐레이션 필터 등 인터랙션 설계.' },
      { step: 'Publishing', desc: 'HTML·CSS·jQuery로 반응형 마크업과 스크롤 애니메이션 구현.' },
    ],
    decisions: [
      { title: '콘텐츠 우선 히어로', desc: "기업 태그라인 중심이던 첫 화면을 'It's time to dingo' 카피·추천 아티스트로 바꿔 콘텐츠 감성을 강조." },
      { title: '믿고 보는 큐레이션', desc: '원본의 채널 나열 방식 대신 ALL·LIVE·INTERVIEW·MUSIC 필터로 영상을 한 곳에서 탐색.' },
      { title: '지표 섹션 정돈', desc: '원본에도 있던 구독자·시청시간·콘텐츠 수 롤링 지표를 유지하되 시각적으로 정돈해 신뢰를 강화.' },
      { title: '몰입형 뮤직 플레이어', desc: '원본엔 없던 Killing Voice 바이닐·시크바 인터랙션을 더해 음악 콘텐츠 경험을 강화.' },
    ],
    outcome: 'ChatGPT로 이미지를, Gemini를 활용하여 hero 영상을 제작했습니다. Claude를 활용해 퍼블리싱을 하였습니다. 기업 소개형 첫인상이 콘텐츠 브랜드다운 무드로 바뀌고, 영상·음악 진입 동선이 짧아졌습니다. 메인 페이지 마지막 섹션엔 직접 음악을 들을 수 있는 공간을 마련해 dingo의 음악적 콘텐츠를 돋보이도록 하였습니다.',
    learnings: '메뉴가 많은 브랜드일수록 리디자인은 "새로 그리기"보다 "우선순위 다시 잡기"라는 걸 체감했습니다.',
  },
  'class101': {
    no: 'PROJECT 02', title: 'Class101 리디자인', category: 'Web Redesign', type: 'Web', year: '2026',
    link: 'https://slrspdla-nunu.github.io/Class101/',
    team: false, featured: false, theme: 'light', mock: 'web',
    summary: '온라인 클래스 플랫폼 Class101의 홈 리디자인. 밝은 마켓형 화면을 다크·네온 무드로 바꿔 브랜드 개성과 탐색 흐름을 강화했습니다.',
    pages: ['홈', '클래스 목록', '클래스 상세', '멤버십', '커뮤니티', '커뮤니티 글', '카테고리(일러스트)', '크리에이터 홈', '결제', '로그인', '회원가입', '마이페이지', '내 클래스', '설정'],
    gallery: ['image/class1011.png', 'image/class1012.png', 'image/class1013.png'],
    compare: { before: 'image/class101_before.png', after: 'image/class101_pc.png' },
    role: 'UX/UI · AI 활용 퍼블리싱', contribution: 100,
    tools: ['Figma', 'HTML/CSS', 'JavaScript', 'ChatGPT','Claude'],
    problem: '예전 Class101은 "세상의 모든 클래스를 하나의 구독으로"를 내세웠지만, 클래스가 4,000개 이상으로 많아 무엇부터 볼지 막막하고 밝은 마켓형 화면에서 브랜드 개성이 옅었습니다.',
    goal: '방대한 클래스를 관심사 추천과 명확한 카테고리로 정돈하고, 다크·네온 무드로 브랜드 개성과 몰입감을 높이는 것.',
    process: [
      { step: 'Research', desc: '예전 Class101(구독 모델)의 정보 구조와 탐색·추천 흐름 정리.' },
      { step: 'Flow', desc: '추천 → 카테고리 → 클래스 상세 → 멤버십 흐름 재설계.' },
      { step: 'UI Design', desc: '다크 팔레트 + 네온 옐로우 그라디언트 디자인 시스템 정의.' },
      { step: 'Interaction', desc: 'Swiper 히어로 슬라이더·아코디언 메가메뉴·드래그 캐러셀·카드 hover 설계.' },
      { step: 'Publishing', desc: 'HTML·CSS·바닐라 JS로 멀티페이지 구현(로그인은 localStorage 목업).' },
    ],
    decisions: [
      { title: '무드 대전환', desc: '밝은 마켓형 화면을 다크 배경 + 네온 옐로우 포인트로 바꿔 브랜드 개성과 몰입감을 강화.' },
      { title: '추천 우선', desc: '"님을 위한 추천 클래스"처럼 첫 화면을 관심사 추천으로 시작해 진입 장벽을 낮춤.' },
      { title: '메가메뉴 카테고리', desc: '일러스트·공예·코딩 등 방대한 분류를 아코디언 메가메뉴로 상시 탐색.' },
      { title: '몰입형 카드·슬라이더', desc: 'Swiper 슬라이더와 hover glow·zoom 카드로 클래스 탐색에 리듬감을 더함.' },
    ],
    outcome: 'ChatGPT를 활용해 배너 이미지를 생성하고, 레이아웃 제작에 도움을 받았습니다. 퍼블리싱은 Claude를 활용하였습니다. 탐색 피로를 줄이면서, 밋밋하던 브랜드 인상을 또렷한 다크·네온 무드로 끌어올렸습니다.',
    learnings: '레퍼런스를 그대로 베끼기보다 브랜드 톤을 재해석하는 게 리디자인의 핵심임을 배웠습니다.',
  },
  'purrcare': {
    no: 'PROJECT 03', title: 'PurrCare 쇼핑몰', category: 'Commerce', type: 'Commerce', year: '2026',
    link: 'https://slrspdla-nunu.github.io/0610_purrcare/',
    team: false, featured: true, theme: 'light', mock: 'shop',
    summary: 'PurrCare — "일상에 행복을 더하는" 고양이 전용 용품 브랜드를 직접 기획한 쇼핑몰 (개인 프로젝트).',
    pages: ['홈', '상품 목록', '베스트셀러', '상품 상세 (3종)', '장바구니', '위시리스트', '마이페이지', '공지사항', '공지 상세', '공지 작성', '로그인', '회원가입'],
    gallery: ['image/purrcare_web1.png', 'image/purrcare_web2.png', 'image/purrcare_web3.png'],
    main: 'image/purrcare_web_v.png',
    role: '기획 · 브랜딩 · UI/UX · AI 활용 퍼블리싱', contribution: 100,
    tools: ['Figma', 'HTML/CSS', 'JavaScript', 'ChatGPT','Claude'],
    problem: '실제 브랜드가 아니라, 고양이의 건강·행복을 앞세운 반려묘 용품 브랜드 "PurrCare"를 콘셉트부터 직접 만든 프로젝트입니다. 상품이 많은 커머스는 자칫 산만해지고 브랜드 인상이 옅어지기 쉬운데, 따뜻한 브랜드 무드와 상품 가독성을 함께 잡는 것이 스스로 세운 과제였습니다.',
    goal: '상품이 주인공이 되는 정돈된 그리드에 "일상에 행복을 더하는" 따뜻한 브랜드 톤을 얹어, 신뢰감 있고 기분 좋은 쇼핑 경험을 콘셉트부터 화면까지 하나로 잇는 것.',
    process: [
      { step: 'Branding', desc: '"일상에 행복을 더하는" 콘셉트로 고양이·따뜻함을 담은 브랜드 톤·컬러·로고 방향 정의.' },
      { step: 'IA', desc: '홈·상품 목록·상세·장바구니·위시리스트·공지·마이페이지까지 쇼핑 플로우 설계.' },
      { step: 'UI Design', desc: '상품 중심 카드 그리드 + 절제된 컬러로 상품이 돋보이는 화면 구성.' },
      { step: 'Publishing', desc: 'PC·모바일 반응형으로 구현.' },
    ],
    decisions: [
      { title: '브랜드부터 화면까지', desc: '기존 몰을 참고하기보다 PurrCare의 콘셉트·톤을 먼저 세우고 사이트 전체에 일관 적용.' },
      { title: '상품 우선', desc: '장식을 줄여 상품 이미지가 주인공이 되게 하고, 따뜻한 컬러는 포인트로만 사용.' },
      { title: '일관된 제품 카드', desc: '브랜드·상품명·가격 위계를 통일해 목록 탐색을 정돈.' },
      { title: '완결된 쇼핑 플로우', desc: '상품 상세·장바구니·위시리스트·마이페이지·공지까지 구현해 실제 몰처럼 완성.' },
    ],
    outcome: 'Codex와 ChatGPT를 활용해 이미지를 생성하고, Claude를 활용해 퍼블리싱을 하였습니다. PurrCare 웹앱과 연결되는 가상 브랜드를 제작하였고, 콘셉트·무드·쇼핑 플로우가 하나로 이어지는 따뜻하고 정돈된 커머스 사이트를 완성했습니다.',
    learnings: '브랜드를 처음부터 만들 때는 콘셉트가 모든 화면의 기준이 된다는 걸 체감했고, 커머스에서는 "절제"가 곧 상품을 돋보이게 하는 디자인이라는 것도 배웠습니다.',
  },
  'local-community': {
    no: 'PROJECT 04', title: 'HOLO', category: 'App · Team', type: 'App', year: '2026',
    link: 'https://3team-holo.vercel.app/',
    team: true, featured: true, theme: 'light', mock: 'app',
    summary: 'HOLO — 2030 1인 가구를 위한 지역 커뮤니티 앱 (팀 프로젝트). 동네 이웃과 가볍게 연결되면서, 마이룸·레벨 등 재미 요소로 계속 머무는 커뮤니티를 목표로 했습니다.',
    pages: ['스플래시', '로그인·인증', '홈', '게시판 (목록·상세·작성·검색)', '지도', '채팅', '모임', '출석 이벤트', '마이페이지', '친구·알림', '마이룸'],
    gallery: ['image/holo1.png', 'image/holo2.png', 'image/holo3.png'],
    galleryMode: 'portrait',
    role: 'UI 디자인 · 게시판 개발 (팀)', contribution: '메인 디자인, 게시판 기능 구현(AI 활용 퍼블리싱)',
    tools: ['Figma', 'React Native', 'Expo', 'TypeScript', 'Supabase'],
    problem: '혼자 사는 2030에게 동네는 가깝지만, 이웃과 자연스럽게 연결될 접점은 많지 않습니다. 부담 없이 동네와 소통하면서도 계속 들여다보고 싶은 재미가 있는 지역 커뮤니티 앱을 팀으로 만들었습니다.',
    goal: '동네 글·모임·채팅을 한 앱에서 가볍게 주고받고, 마이룸·출석·레벨 같은 재미 요소로 자연스럽게 다시 찾게 만드는 것.',
    process: [
      { step: 'Research', desc: '1인 가구의 동네 생활·커뮤니티 사용 행태 정리(팀).' },
      { step: 'IA', desc: '홈·게시판·지도·채팅·마이페이지 등 앱 전체 구조 설계(팀).' },
      { step: 'UI Design', desc: '메인 디자이너로서 톤·컴포넌트와 핵심 화면 UI를 담당.' },
      { step: 'Build', desc: '게시판(목록·상세·작성·검색) 기능을 AI를 활용한 퍼블리싱으로 구현.' },
    ],
    decisions: [
      { title: '메인 디자인 담당', desc: '앱 전반의 톤·컴포넌트·핵심 화면을 설계해 팀 화면들의 일관성을 잡음.' },
      { title: '게시판 직접 구현', desc: '디자인과 함께 게시판(목록·상세·작성·검색) 기능을 바이브 코딩으로 구현.' },
      { title: '머무르게 하는 재미', desc: '마이룸·출석·레벨 등 게임 요소로 단순 정보 앱을 넘어 다시 찾을 동기를 부여.' },
      { title: '가벼운 참여', desc: '글쓰기·소통 단계를 줄여 혼자 사는 사용자도 부담 없이 참여하게 함.' },
    ],
    outcome: 'ChatGPT를 활용해 이미지를 생성하고, Claude를 활용해 퍼블리싱을 하였습니다. 동네 소통(게시판·채팅·모임)과 재미 요소(마이룸·레벨)를 갖춘 커뮤니티 앱을 팀으로 완성했고, 저는 메인 디자인과 게시판 구현을 맡았습니다.',
    learnings: '규모 있는 팀 프로젝트에서 메인 디자이너로 디자인 시스템을 먼저 세워 화면 간 일관성을 지키는 일의 중요성과, 디자인한 화면을 직접 구현하며 디자인–개발 간극을 좁히는 경험을 얻었습니다.',
  },
  'imagination-door': {
    no: 'PROJECT 05', title: '상상의 문 리디자인', category: 'Web Redesign · Team', type: 'Web', year: '2026',
    link: 'https://doorlove1234-coder.github.io/sangsangDoor/',
    team: true, featured: false, theme: 'light', mock: 'web',
    summary: '방탈출 카페 "상상의 문" 홈페이지 리디자인 (팀 프로젝트). 기능 나열형 예약 사이트를 문·카드 콘셉트의 몰입형 브랜드 경험으로 바꾸었습니다.',
    pages: ['홈', '테마', '예약', '예약 확인', '매장 안내', '스토리', '공지사항', '제휴', '개인정보처리방침', '관리자'],
    gallery: ['image/sangsnagdoor1.png', 'image/sangsnagdoor2.png', 'image/sangsnagdoor3.png'],
    compare: { before: 'image/sangsnagdoor_before.png', after: 'image/sangsnagdoor_after.png' },
    role: 'UI 디자인 (팀 3인)', contribution: '메인 디자인, AI 활용 퍼블리싱',
    tools: ['Figma', 'HTML/CSS', 'JavaScript', 'ChatGPT','Claude'],
    problem: '원본은 여러 지점·테마를 장르·난이도·시간 정보 위주로 나열하는 기능형 예약 사이트라, 방탈출 특유의 몰입감과 브랜드 무드가 첫 화면에서 느껴지지 않았습니다.',
    goal: '테마를 단순 나열하는 대신 "문을 열고 들어간다"는 콘셉트로 기대감을 주면서, 지점·테마 탐색과 예약까지 매끄럽게 잇는 것.',
    process: [
      { step: 'Audit', desc: '원본의 지점·테마·실시간예약 동선과 정보 구조 점검(팀).' },
      { step: 'Concept', desc: '문·카드 은유의 브랜드 콘셉트와 다크 몰입 무드 설정.' },
      { step: 'Wireframe', desc: '히어로 → 지점별 베스트 → 스토리 → 예약 흐름 재설계.' },
      { step: 'UI Design', desc: '담당 섹션 비주얼과 테마 카드·예약 화면 디자인.' },
      { step: 'Build', desc: '예약·예약확인 등 실제 예약 플로우를 팀에서 구현.' },
    ],
    decisions: [
      { title: '몰입형 히어로', desc: '테마 목록부터 보여주던 첫 화면을 "카드를 뽑아보세요"·문 일러스트로 바꿔 방탈출 특유의 기대감을 연출.' },
      { title: '지점별 베스트', desc: '여러 지점을 탭으로 나눠 지점별 인기 테마를 먼저 노출.' },
      { title: '브랜드 스토리', desc: '"상상의 문, 그 이야기"를 4단 서사로 담아 단순 예약 사이트를 브랜드 경험으로 확장.' },
      { title: '예약 플로우 정돈', desc: '테마 → 지점 → 예약, 그리고 예약 확인까지 동선을 명확히 정리.' },
    ],
    outcome: 'ChatGPT를 활용해 이미지를 생성하고, Claude를 활용해 퍼블리싱을 하였습니다. 정보 나열형이던 예약 사이트가 다크 무드의 몰입형 브랜드 경험으로 바뀌고, 테마 탐색부터 예약·확인까지 흐름이 또렷해졌습니다. 팀원들과 제안서를 만들어 본사에 제출하였습니다.',
    learnings: '팀 협업에서 브랜드 콘셉트(문·카드)와 디자인 시스템을 먼저 합의하니 화면 간 톤이 흔들리지 않았습니다. 중심을 잡는 것이 중요하다는 것을 배웠습니다.',
  },
  'wolfram-alpha': {
    no: 'PROJECT 06', title: '울프람알파 리디자인', category: 'Web Redesign · Team', type: 'Web', year: '2026',
    figmaProto: 'https://www.figma.com/proto/imFRSwAPpB6DtefqHXhxDH/1%ED%8C%80-%ED%8C%80%ED%94%8C--03-24-TEST_%ED%9D%AC%EC%A7%84?node-id=301-6234&t=mIANDwY7EVm9YTag-0&scaling=min-zoom&content-scaling=fixed&page-id=85%3A1301&starting-point-node-id=301%3A6234',
    team: true, featured: false, theme: 'light', mock: 'web',
    summary: '연산 지식엔진 WolframAlpha 홈 리디자인 (팀 프로젝트). 영문·검색 위주의 딱딱한 도구를 한국어 친화적이고 따뜻한 탐색형 서비스로 바꾸었습니다.',
    pages: ['홈', '결과(Q&A)', '수학 예제', '과학기술 예제', '사회문화 예제', '일상생활 예제'],
    gallery: ['image/wolfram1.png', 'image/wolfram2.png', 'image/wolfram3.png'],
    compare: { before: 'image/wolfram_before.png', after: 'image/wolfram_after.png' },
    figmaProtoMobile: 'https://www.figma.com/proto/imFRSwAPpB6DtefqHXhxDH/1%ED%8C%80-%ED%8C%80%ED%94%8C--03-24-TEST_%ED%9D%AC%EC%A7%84?node-id=354-6733&viewport=-2795%2C3920%2C0.12&t=ZEi5GTk0JkfLBDkk-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=117%3A1448&page-id=85%3A1301',
    figmaProtoPC: 'https://www.figma.com/proto/imFRSwAPpB6DtefqHXhxDH/1%ED%8C%80-%ED%8C%80%ED%94%8C--03-24-TEST_%ED%9D%AC%EC%A7%84?node-id=301-6234&viewport=-6957%2C10198%2C0.3&t=NEirVOgteYXdZqgR-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=301%3A6234&show-proto-sidebar=1&page-id=85%3A1301',
    role: 'UI 디자인 (팀 3인)', contribution: '메인 디자인',
    tools: ['Figma'],
    problem: '원본 WolframAlpha는 강력한 계산 엔진이지만 영문 중심에 예시가 목록으로 나열돼, 첫 화면이 딱딱하고 "무엇을 물어볼 수 있는지" 감이 잘 오지 않았습니다.',
    goal: '강력한 계산 기능과 4개 주제 구조(수학·과학기술·사회문화·일상생활)는 유지하되, 한국어 자연어 검색과 주제별 탐색·예시로 진입 경험을 끌어올리는 것.',
    process: [
      { step: 'Analyze', desc: '원본의 검색 중심 구조와 4개 주제 IA·전문가 톤 정리(팀).' },
      { step: 'Concept', desc: '따뜻한 오렌지 그라디언트 + 3D 일러스트의 친근한 브랜드 무드 설정.' },
      { step: 'Flow', desc: '검색 → 주제별 탐색 → 예제 카테고리 → 결과(Q&A) 흐름 재설계.' },
      { step: 'UI Design', desc: '자연어/수학기호 탭 검색창·주제 카드·결과 화면 등 담당 화면 디자인.' },
      { step: 'Prototype', desc: 'Figma로 화면 연결·인터랙션 프로토타입 제작.' },
    ],
    decisions: [
      { title: '한국어 자연어 검색', desc: '영문 위주 입력을 자연어/수학기호 탭과 한국어 예시 질문 칩으로 바꿔 진입 장벽을 낮춤.' },
      { title: '주제별 탐색 카드', desc: '나열식 예시 목록을 수학·과학기술·사회문화·일상생활 4개 카드와 3D 일러스트로 정리해 친근하게.' },
      { title: '풀어주는 Q&A 결과', desc: '결과를 "정답" 카드로 강조하고 경고·차트·재계산 입력을 함께 배치해 이해와 다음 시도를 도움.' },
      { title: '사용감 확립', desc: '"지금 N명이 풀고 있어요" 카운터와 예시 카드로 딱딱한 도구를 써보고 싶게 만듦.' },
    ],
    outcome: '검색·영문 위주의 딱딱한 첫인상이 한국어 친화적이고 따뜻한 탐색형 경험으로 바뀌고, "무엇을 물어볼 수 있는지"가 첫 화면에서 드러나도록 디자인하였습니다.',
    learnings: '강력한 기능일수록 "무엇을 할 수 있는지 보여주는" 온보딩이 중요하다는 걸 배웠고, 원본의 정보 구조는 존중하면서 톤을 재해석하는 리디자인 감각을 익혔습니다.',
  },
  'hogwarts': {
    no: 'PROJECT 07', title: '호그와트 레거시 리디자인', category: 'Web Redesign', type: 'Web', year: '2026',
    link: 'https://slrspdla-nunu.github.io/hogwart/',
    team: false, featured: true, theme: 'dark', mock: 'web',
    summary: '게임 「호그와트 레거시」 공식 홈페이지를 세계관 몰입형으로 재해석한 리디자인 (개인 프로젝트).',
    pages: ['메인 (기숙사 배정 퀴즈)', '주문 도감 (갤러리)', '학습 가이드 (마법책 UI)', '예언자일보 (뉴스)', '방명록 (커뮤니티)'],
    gallery: ['image/hogwart1.png', 'image/hogwart2.png', 'image/hogwart3.png'],
    compare: { before: 'image/hogwart_before.png', after: 'image/hogwart_pc.png' },
    role: 'UI/UX · 인터랙션 · AI 활용 퍼블리싱', contribution: 100,
    tools: ['Figma', 'HTML/CSS', 'JavaScript', 'ChatGPT', 'Claude', 'Codex'],
    problem: '「호그와트 레거시」 공식 홈페이지는 트레일러·게임 소개·구매(지금 획득)로 이어지는 마케팅 랜딩 페이지에 가까워, 정보 전달과 구매 유도에는 효율적이지만 마법 세계의 "분위기"를 체험하기엔 아쉬웠습니다. 게임을 "소개받는" 느낌은 있어도 그 세계에 "들어와 있는" 느낌은 약했습니다.',
    goal: '공식 사이트의 핵심 구성(미디어·FAQ·커뮤니티)은 지키되, 방문 자체가 마법 세계에 들어온 경험이 되도록 재해석하는 것. 어둡지만 칙칙하지 않은 무드와 페이지별 세계관 소품(도감·마법책·신문)으로 몰입감을 주면서 정보 가독성은 유지하는 것을 목표로 했습니다.',
    process: [
      { step: 'Analysis', desc: '공식 홈페이지의 구조(히어로·게임 소개·미디어·FAQ·커뮤니티·구매)와 톤을 분석해 무엇을 남기고 무엇을 다르게 말할지 리디자인 방향 설정.' },
      { step: 'Moodboard', desc: '조명·안개·금속·양피지 질감 레퍼런스로 "어둡지만 따뜻한" 톤과 Cinzel 세리프 타이포 시스템 정의.' },
      { step: 'IA', desc: '공식 섹션을 세계관 소품으로 재구성 — 미디어→주문 도감, FAQ→학습 가이드, 커뮤니티→예언자일보·방명록, 여기에 기숙사 배정 메인을 더해 5개 페이지 설계.' },
      { step: 'UI & Publishing', desc: '편지·양피지·신문·마법책 은유로 화면을 구성하고, HTML·CSS·JS로 기숙사 배정 퀴즈·골든 스니치·조명 토글 등 인터랙션 구현.' },
    ],
    decisions: [
      { title: '공식 섹션을 세계관 소품으로', desc: '미디어를 "주문 도감", FAQ를 "마법책", 커뮤니티를 "예언자일보·방명록"으로 번역해, 같은 정보를 세계관 안에서 경험하게 함.' },
      { title: '참여를 만드는 기숙사 배정', desc: '마케팅 랜딩을 관람만 하게 두지 않고, 6문항 기숙사 배정 퀴즈로 방문자를 첫 화면부터 참여자로 끌어들임.' },
      { title: '숨은 마법 인터랙션', desc: '골든 스니치 잡기·조명 토글·물약 효과 등 작은 장치를 숨겨, 구매 버튼 대신 "둘러보는 재미"로 체류를 유도.' },
      { title: '분위기 vs 가독성', desc: '배경은 어둡게 가되 본문은 충분한 대비를 확보하고, 모션은 포인트 구간에만 절제해서 사용.' },
    ],
    outcome: 'Codex와 ChatGPT를 활용해 이미지를 생성하고, Claude를 활용해 퍼블리싱을 하였습니다. 구매 유도 중심의 마케팅 랜딩을, 정보는 그대로 담으면서 세계관을 체험하는 몰입형 사이트로 리디자인했습니다. "분위기가 산다"는 피드백을 받으면서도 정보 전달은 유지했습니다.',
    learnings: '리디자인은 단순히 원본을 예쁘게 바꾸는 게 아니라 "무엇을 남기고 무엇을 다르게 말할지" 정하는 일이라고 생각합니다. 공식 홈페이지의 목적은 지키면서 표현만 세계관으로 변화시키니, 분위기와 정보가 상충하지 않고 함께 갈 수 있었습니다.',
  },
  'dream-diary': {
    no: 'PROJECT 08', title: 'DreamDex', category: 'Web App', type: 'App', year: '2026', wip: true,
    link: 'https://slrspdla-nunu.github.io/Dreamdex/',
    team: false, featured: true, theme: 'light', mock: 'app',
    summary: 'DreamDex — 매일의 꿈을 기록하고 "도감"처럼 수집·분류하는 꿈일기 웹앱 (개인 프로젝트).',
    pages: ['홈', '아카이브', '꿈 기록', '도감', '통계', '꿈 지도', '설정'],
    gallery: ['image/dreamdex1.png', 'image/dreamdex2.png', 'image/dreamdex3.png'],
    role: '기획 · UI/UX · AI 활용 퍼블리싱', contribution: 100,
    tools: ['Figma', 'HTML/CSS', 'JavaScript', 'Firebase' , 'Claude'],
    problem: '꿈이라는 흥미로운 소재를 가볍고 재미있게 기록하고, 그 기록이 쌓여 나만의 패턴이 되도록 만들고 싶었습니다. 단순 일기에 그치지 않고, 나중에 다시 꺼내 볼 때 재미를 느낄 수 있는 꿈일기를 목표로 한 개인 프로젝트입니다.',
    goal: '기록은 가볍게, 다시 보는 경험은 재미있게. 쌓인 꿈을 도감·통계·지도로 패턴화해 볼수록 흥미로운 꿈일기를 만드는 것.',
    process: [
      { step: 'Concept', desc: '"꿈을 수집한다"는 도감(Dex)형 콘셉트와 몽환적이되 차분한 무드 정의.' },
      { step: 'Flow', desc: '기록 → 아카이브 → 도감·통계·꿈 지도로 돌아보는 앱 플로우 설계.' },
      { step: 'UI Design', desc: '큰 입력 영역·태그로 빠른 기록, 카드형 도감·통계 화면 구성.' },
      { step: 'Build', desc: 'HTML·CSS·JS 단일 페이지 앱(SPA)으로 구현하고, Firebase(구글 로그인)로 기록을 저장·기기 간 동기화.' },
    ],
    decisions: [
      { title: '도감형 수집', desc: '꿈을 기록만 하지 않고 "도감(Dex)"으로 수집·분류해 모으는 재미와 다시 보는 동기를 부여.' },
      { title: '1분 기록', desc: '입력 단계를 최소화해 잠에서 깬 직후에도 부담 없이 남기도록 설계.' },
      { title: '패턴을 보는 회고', desc: '통계와 꿈 지도로 반복되는 테마·감정을 한눈에 돌아보게 함.' },
      { title: '어디서든 이어보기', desc: '구글 로그인과 클라우드 동기화로 기기를 옮겨도 기록이 그대로 유지되게 함.' },
    ],
    outcome: 'Claude를 활용해 퍼블리싱을 하였습니다. 단순 일기를 넘어, 꿈을 모으고(도감) 패턴을 돌아보는(통계·지도) 흐름까지 갖춘 꿈일기 웹앱을 완성했습니다.',
    learnings: '기록형 어플은 "얼마나 부담 없이 남기느냐"가 핵심이고, 여기에 "모으는 재미"를 더하면 다시 찾게 되는 동기가 생긴다는 걸 배웠습니다.',
  },
  'altitude': {
    no: 'PROJECT 09', title: 'ALTITUDE', category: 'Commerce', type: 'Commerce', year: '2026',
    link: 'https://slrspdla-nunu.github.io/ALTITUDE/',
    team: false, featured: false, theme: 'light', mock: 'web',
    summary: 'ALTITUDE — 고산·익스페디션 무드로 직접 기획한 가상 아웃도어 브랜드의 커머스 사이트 (개인 프로젝트).',
    role: '기획 · 브랜딩 · UI/UX ·\nAI 활용 퍼블리싱', contribution: 100,
    tools: ['Figma', 'HTML/CSS', 'JavaScript', 'ChatGPT', 'Claude', 'Codex'],
    pages: ['홈', '스토어', '컬렉션', '익스페디션 라인', '상품 상세 (2종)', '장바구니', '결제', '주문 완료', '주문 내역', '위시리스트', '마이페이지', '프로필 수정', '로그인', '회원가입', '브랜드 스토리', '테크놀로지', 'FAQ', '사이즈 가이드', '매장 찾기', '문의', '리뷰 작성'],
    gallery: ['image/ALTITUDE1.png', 'image/ALTITUDE2.png', 'image/ALTITUDE3.png'],
    main: 'image/ALTITUDE_v.png',
    problem: '실제 클라이언트가 아니라, 고산 등반을 지향하는 아웃도어 브랜드 "ALTITUDE"를 이름과 콘셉트부터 직접 만든 프로젝트입니다. 스펙 정보가 많은 아웃도어 커머스는 자칫 카탈로그처럼 딱딱해지기 쉬운데, 브랜드의 익스페디션 무드를 그 안에 어떻게 함께 담을지가 스스로 세운 과제였습니다.',
    goal: '제품 신뢰도(스펙·기능)를 지키면서도 히어로·컬렉션과 스크롤 인터랙션으로 익스페디션의 몰입감을 주고, 브랜드 콘셉트부터 화면까지 하나로 잇는 것.',
    process: [
      { step: 'Branding', desc: '브랜드 네이밍·콘셉트(ALTITUDE=고도)부터 설산·금속 질감 키워드로 톤&매너·타이포 시스템 정의.' },
      { step: 'IA', desc: '스토어·익스페디션 라인·상품 상세·장바구니·결제·주문·위시리스트·마이페이지까지 전체 쇼핑 플로우 설계.' },
      { step: 'UI Design', desc: '제품이 주인공이 되는 그리드 + 스펙 위계 정리, 컬렉션 히어로와 스토리·테크놀로지 페이지 구성.' },
      { step: 'Publishing', desc: 'HTML·CSS·JS로 스크롤 리빌·호버·검색·모바일 내비 등 인터랙션을 반응형으로 구현.' },
    ],
    decisions: [
      { title: '브랜드부터 화면까지', desc: '기존 브랜드를 참고하기보다 네이밍·콘셉트를 먼저 세우고, 그 무드를 사이트 전체에 일관되게 적용.' },
      { title: '무드와 정보의 균형', desc: '히어로·컬렉션은 감성적으로, 상품 상세는 스펙 중심으로 역할을 분리.' },
      { title: '일관된 제품 카드', desc: '브랜드·제품명·가격 위계를 통일해 목록 탐색을 정돈.' },
      { title: '진짜 같은 쇼핑 플로우', desc: '장바구니·결제·주문내역·위시리스트·마이페이지까지 구현해 실제 커머스처럼 완결.' },
    ],
    outcome: 'Codex와 ChatGPT를 활용해 이미지를 생성하고, Claude를 활용해 퍼블리싱을 하였습니다. 가상 브랜드지만 콘셉트·무드·쇼핑 플로우가 하나로 이어지는, 실제 같은 커머스 사이트를 완성했습니다.',
    learnings: '브랜드를 처음부터 만들 때는 "이름과 콘셉트"가 모든 화면 결정의 기준이 된다는 걸 체감했고, 커머스에서 분위기는 구매를 방해하지 않는 선에서 얹을 때 가장 효과적이라는 것도 배웠습니다.',
  },
  'purrcare-app': {
    no: 'PROJECT 10', title: 'PurrCare 웹앱', category: 'Web App', type: 'App', year: '2026', wip: true,
    link: 'https://slrspdla-nunu.github.io/purrcare-web-app/',
    team: false, featured: false, theme: 'light', mock: 'app',
    summary: '반려묘의 건강·기록·일정을 한 곳에서 관리하는, 직접 기획·개발한 반려묘 케어 웹앱 (개인 프로젝트, 제작 중).',
    pages: ['대시보드', '내 고양이', '기록', '건강 (병원 찾기·AI 상담)', '일정', '커뮤니티', '입양', '마이페이지', '설정', '스토어'],
    role: '기획 · UI/UX · AI 활용 퍼블리싱', contribution: 100,
    tools: ['Figma', 'HTML/CSS', 'JavaScript', 'Claude'],
    problem: '반려묘의 병원 기록·증상·예방접종 일정이 메모장·사진첩·기억에 흩어져 있어, 정작 병원에서 물어보면 한눈에 답하기 어려웠습니다. 여러 마리를 키우면 더 헷갈렸고요. 흩어진 케어 정보를 고양이별로 한 곳에 모으는 앱을 직접 만들어보고 싶었습니다.',
    goal: '고양이별로 건강 기록·일정을 쌓고 대시보드에서 상태를 빠르게 확인하는 관리 도구. 여기에 병원 찾기·커뮤니티·입양·스토어까지 더해, 집사의 하루를 한 앱에서 돌보는 것을 목표로 했습니다.',
    process: [
      { step: 'Define', desc: '집사의 케어 시나리오(증상·병원·체중·예방접종·일정)를 정리해 "고양이 중심"의 정보 구조 설계.' },
      { step: 'Flow', desc: '대시보드·내 고양이·기록·건강·일정·커뮤니티·입양·마이페이지·설정으로 뷰를 구성하고, 데스크톱 사이드바 ↔ 모바일 하단 탭 반응형 설계.' },
      { step: 'UI Design', desc: '고양이 등록/전환, 커스텀 캘린더·필터, 카드형 기록에 6종 라이트 테마(차콜·세이지·라떼 등) 디자인 시스템 구성.' },
      { step: 'Build', desc: '프레임워크 없이 HTML·CSS·JS로 뷰 전환형 SPA 구현. localStorage로 기록을 저장하고, 병원 지도·AI 상담·입양은 데모로 인터랙션 설계.' },
    ],
    decisions: [
      { title: '고양이 중심 구조', desc: '여러 마리를 사진·생일과 함께 등록·전환하며 각자 기록·타임라인을 따로 쌓게 설계.' },
      { title: '빠른 기록', desc: '증상·건강·행동을 날짜/시간 필터와 커스텀 캘린더로 최소 단계에 남기도록 입력 흐름을 단순화.' },
      { title: '케어를 넘어 하루로', desc: '기록만이 아니라 병원 찾기·커뮤니티·입양·스토어까지 묶어 집사의 일상을 한 앱에서 잇도록 확장.' },
      { title: '내 취향의 앱', desc: '6가지 테마와 발자국 커서 등 디테일로, 매일 여는 앱에 애착이 가도록 함.' },
    ],
    outcome: 'Claude를 활용해 퍼블리싱을 하였습니다. 흩어져 있던 반려묘 정보를 고양이별로 기록·회고하고, 병원·커뮤니티·입양까지 한 앱에서 다루는 반려묘 케어 웹앱을 만들었습니다. (디자인 및 일부 기능은 데모 단계로, 계속 다듬는 중입니다.)',
    learnings: '기록형 앱은 "얼마나 빨리·부담 없이 남기느냐"가 핵심 사용성이라는 걸 다시 확인했고, 기능을 넓힐수록 "고양이 중심"이라는 하나의 축을 잃지 않는 게 더 중요하다는 걸 배웠습니다.',
  },
  'witch-delivery-game': {
    no: 'PROJECT 11', title: '마녀 배달부의 비상착륙', category: 'Mobile Web Game', type: 'App', year: '2026', wip: true,
    link: 'https://slrspdla-nunu.github.io/witch-delivery-game/',
    team: false, featured: false, theme: 'dark', mock: 'app',
    summary: '꼬마 마녀 루나가 고양이 네로와 함께 빗자루로 물품을 배달하는, 달빛 하늘 도시 배경의 모바일 웹 게임 (개인 프로젝트).',
    pages: ['스플래시', '메인 메뉴', '의뢰 선택', '비행 게임(HUD)', '성공 / 실패', '스토리 모드'],
    gallery: ['image/witch_delivery_game1.png', 'image/witch_delivery_game2.png', 'image/witch_delivery_game3.png'],
    galleryMode: 'portrait',
    role: '게임 기획 · UI · 인터랙션 · AI 활용 퍼블리싱', contribution: 100,
    tools: ['HTML/CSS', 'JavaScript', 'PixiJS', 'ChatGPT', 'Claude', 'Codex', 'Suno'],
    problem: '모바일 세로 화면에서 판타지 게임의 세계관·조작·상태 정보(HP·MP·시간·거리)를 짧은 흐름 안에 이해시키고, 웹만으로 "게임다운" 몰입감을 내는 것이 과제였습니다.',
    goal: '스플래시·메인에서 세계관을 전하고, 의뢰를 골라 빗자루 비행으로 이어지는 한 판을 완결하는 것. 물리 기반 비행과 스킬·별점으로 웹에서도 게임처럼 즐기게 만드는 것을 목표로 했습니다.',
    process: [
      { step: 'Concept', desc: '달빛 하늘 도시와 마녀 배달부 루나·고양이 네로 콘셉트로 게임 무드와 한 판의 흐름(의뢰→비행→결과)을 정의.' },
      { step: 'UI Design', desc: '세로 화면에 맞춰 메인 메뉴, 2×2 의뢰 카드(난이도·보상), HP·MP·시간·거리 HUD, 조작·일시정지 버튼 배치.' },
      { step: 'Game Design', desc: '물리 기반 비행(가속·관성), 까마귀 장애물, 별사탕·모래시계·물약 아이템, 대시·방어막 스킬(쿨다운), 50초 제한·별점(1~3★) 규칙 설계.' },
      { step: 'Build', desc: 'HTML·CSS·바닐라 JS로 화면 전환을 구현하고, PixiJS 메시 애니메이션으로 캐릭터를, BGM으로 분위기를 더함.' },
    ],
    decisions: [
      { title: '한 판으로 완결되는 흐름', desc: '의뢰 선택 → 비행 → 성공·실패까지 짧게 끝나는 루프로, 모바일에서 부담 없이 한 판을 즐기게 함.' },
      { title: '물리 비행 + 스킬', desc: '가속·관성 있는 비행에 대시·방어막(MP·쿨다운)을 얹어, 단순 조작을 넘어 판단이 필요한 손맛을 만듦.' },
      { title: '결과를 보상하는 연출', desc: '성공은 별점·글리터·루나 플로팅, 실패는 비·차가운 톤으로 — 결과 화면을 감정적으로 마무리해 다시 하고 싶게 함.' },
      { title: 'PixiJS 캐릭터 연출', desc: '메시 변형 애니메이션으로 정적인 웹 화면보다 게임에 가까운 캐릭터 움직임을 구현.' },
    ],
    outcome: 'BGM은 Suno, 이미지는 ChatGPT·Codex, 퍼블리싱은 Claude를 활용하여 제작했습니다. 스플래시·메인·의뢰 선택·비행·성공/실패·스토리 모드까지 한 판이 완결되는 판타지 모바일 웹 게임 프로토타입을 만들었습니다.',
    learnings: '웹에서도 물리 기반 조작·스킬·별점 같은 게임 규칙과 PixiJS 애니메이션을 얹으면 게임처럼 느껴진다는 걸 배웠습니다.',
  },
};

const ORDER = ['local-community', 'imagination-door', 'wolfram-alpha', 'dingo', 'class101', 'purrcare', 'hogwarts', 'dream-diary', 'purrcare-app', 'altitude', 'witch-delivery-game'];

/* ARCHIVE 카드 썸네일 (slug → 이미지). object-fit:cover 로 꽉 차게 표시.
   매핑 없으면 그라디언트 플레이스홀더로 표시됨. */
const THUMBS = {
  'dingo': 'image/thumbnail_dingo.png',
  'class101': 'image/thumbnail_class101.png',
  'purrcare': 'image/thumbnail_purrcare_web.png',
  'local-community': 'image/thumbnail_holo.png', // 배열이면 여러 장 나란히(contain)
  'imagination-door': 'image/thumbnail_sangsnagdoor.png',
  'wolfram-alpha': 'image/thumbnail_wolfram.png',
  'hogwarts': 'image/thumbnail_hogwart.png',
  'dream-diary': 'image/thumbnail_dreamdex.png',
  'altitude': 'image/thumbnail_ALTITUDE.png',
  'purrcare-app': 'image/thumbnail_purrcare_webapp.png',
  'witch-delivery-game': 'image/thumbnail_witch_delivery_game.png',
};

/* ARCHIVE 카드 말풍선용 한 줄 요약 (slug → 짧은 한 줄). 없으면 summary로 폴백. */
const TAGLINES = {
  'dingo': '영상 콘텐츠 브랜드 Dingo 홈 리디자인',
  'class101': '온라인 클래스 플랫폼 Class101 홈 리디자인',
  'purrcare': '고양이 용품 브랜드 PurrCare 쇼핑몰',
  'local-community': '동네 이웃과 연결되는 지역 커뮤니티 앱',
  'imagination-door': '방탈출 카페 상상의 문 홈 리디자인',
  'wolfram-alpha': '연산 지식엔진 WolframAlpha 홈 리디자인',
  'hogwarts': '게임 세계관을 담은 인터랙티브 팬 사이트',
  'dream-diary': '매일의 꿈을 기록하는 꿈일기 웹앱',
  'altitude': '고산 무드의 아웃도어 커머스',
  'purrcare-app': '반려묘 건강·일정을 관리하는 케어 웹앱',
  'witch-delivery-game': '달빛 하늘 도시를 나는 마녀 배달 게임',
};

/* 그래픽 작업물 (라이트박스).
   type: Banner | Mobile | Poster | Program(식순지)  → GRAPHIC 필터 기준
   단일:  { type:'Poster', title:'...', img:'image/poster2.png' }
   앞뒤:  { type:'Poster', title:'...', slides:[{img:'..._front.jpg'},{img:'..._back.jpg'}] }
          → 한 카드로 묶여 라이트박스에서 자동으로 앞↔뒤 전환 */
const GRAPHICS = [
  // 배너 (마퀴) — 기존 15개 유지 + 신규 1개 추가
  { type: 'Banner', title: '배너 01', img: 'image/banner1.png' },
  { type: 'Banner', title: '배너 02', img: 'image/banner2.png' },
  { type: 'Banner', title: '배너 03', img: 'image/banner3.png' },
  { type: 'Banner', title: '배너 04', img: 'image/banner4.png' },
  { type: 'Banner', title: '배너 05', img: 'image/banner5.png' },
  { type: 'Banner', title: '배너 06', img: 'image/banner6.png' },
  { type: 'Banner', title: '배너 07', img: 'image/banner7.png' },
  { type: 'Banner', title: '배너 08', img: 'image/banner8.png' },
  { type: 'Banner', title: '배너 09', img: 'image/banner9.png' },
  { type: 'Banner', title: '배너 10', img: 'image/banner10.png' },
  { type: 'Banner', title: '배너 11', img: 'image/banner11.png' },
  { type: 'Banner', title: '배너 12', img: 'image/banner12.png' },
  { type: 'Banner', title: '배너 13', img: 'image/banner13.png' },
  { type: 'Banner', title: '배너 14', img: 'image/banner14.png' },
  { type: 'Banner', title: '배너 15', img: 'image/banner15.png' },
  { type: 'Banner', title: '배너 16', img: 'image/banner16.jpg' },
  // 모바일 배너 (신규)
  { type: 'Mobile', title: '모바일 배너 01', img: 'image/mo_banner1.png' },
  { type: 'Mobile', title: '모바일 배너 02', img: 'image/mo_banner2.png' },
  { type: 'Mobile', title: '모바일 배너 03', img: 'image/mo_banner3.png' },
  { type: 'Mobile', title: '모바일 배너 04', img: 'image/mo_banner4.png' },
  // 포스터 (신규) — poster01은 앞/뒤
  { type: 'Poster', title: '포스터 01', slides: [{ img: 'image/poster1_front.jpg' }, { img: 'image/poster1_back.jpg' }] },
  { type: 'Poster', title: '포스터 02', img: 'image/poster2.png' },
  { type: 'Poster', title: '포스터 03', img: 'image/poster3.png' },
  { type: 'Poster', title: '포스터 04', img: 'image/poster4.jpg' },
  { type: 'Poster', title: '포스터 05', img: 'image/poster5.jpg' },
  { type: 'Poster', title: '포스터 06', img: 'image/poster6.jpg' },
  { type: 'Poster', title: '포스터 07', img: 'image/poster7.jpg' },
  { type: 'Poster', title: '포스터 08', img: 'image/poster8.jpg' },
  { type: 'Poster', title: '포스터 09', img: 'image/poster9.jpg' },
  // 식순지 (신규) — 앞/뒤
  { type: 'Program', title: '식순지', slides: [{ img: 'image/Program_front.jpg' }, { img: 'image/Program_back.jpg' }] },
];
